### ISSUE TITLE
It broke

### ISSUE THREAD

**Issue by Kinrany** [sergeysova/this_week_in_rust.rs#4]
There was no place to talk about https://t.me/this_week_in_rust/2119. There is now.

**Comment by va-an** [comment]
@sergeysova, hello!
I'm got some troube with this line:

https://github.com/sergeysova/this_week_in_rust.rs/blob/bea8f4c298c17761f1c380ed513cd4f307ca999d/src/main.rs#L52

---
When I tried run app, I got this output:
```
Error: Io(Custom { kind: NotFound, error: "path not found" })
[Finished running. Exit status: 1]
```

I changed this line to:

```rust
dotenv().ok();
```

... and got some output from app:

```
Reading last-id at: Some("./this_week_in_rust.last_id")
Last ID: 0
Starting fetch articles list...

// ——— //
Fetching #421 — https://this-week-in-rust.org/blog/2021/12/15/this-week-in-rust-421/
Error: IdNotFound
[Finished running. Exit status: 1]
```

This is looks line working app state, or there is any other problems?

**Comment by Kinrany** [comment]
The `IdNotFound` error is being thrown in ~~two~~ three places in [parser.rs](https://github.com/sergeysova/this_week_in_rust.rs/blob/master/src/parsers.rs). One of the parsers is failing because HTML layout of the page has changed.

**Comment by sergeysova** [comment]
Let's check how it works after #5
